from .inner_tilt_env_cfg import BipedInnerTiltEnvCfg
from .outer_vel_pid_env_cfg import BipedOuterVelPIDEnvCfg
from .outer_vel_direct_env_cfg import BipedOuterVelDirectEnvCfg
from .unified_vel_pid_env_cfg import BipedUnifiedVelEnvCfg
